name: Size Limit

on:

  push:
    branches:
      - master
      - dev

  pull_request:
    branches:
      - master
      - dev

jobs:

  sizelimit:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        os: [windows-latest, ubuntu-latest]

    steps:

      - name: Setup repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Test size
        run: npm run size
